-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- This is an example Hyprland config file.

--

-- Refer to the wiki for more information.

--

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

--

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- Execute your favorite apps at launch

-- exec-once = waybar & hyprpaper & firefox




hl.env("XDG_CURRENT_DESKTOP", "sway")

-- Source a file (multi-file configs)

-- source = ~/.config/hypr/myColors.conf

-- Set programs that you use

local terminal = "alacritty"

local fileManager = "nautilus"

local menu = "wofi --show drun"

-- Some default env vars.

hl.env("XCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

-- change to qt6ct if you have that

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
    input = {
        kb_layout = "latam",
        kb_variant = {  },
        kb_model = {  },
        kb_options = {  },
        kb_rules = {  },
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false,
        },
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        numlock_by_default = true,
    },
})

hl.config({
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 5,
        --5
        gaps_out = 20,
        --20
        border_size = 5,
        --2
        layout = "dwindle",
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        col = {
            active_border = { colors = { "rgba(aaaa20cc)", "rgba(aaaa20cc)" }, angle = 0 },
            inactive_border = "rgba(000000bb)",
        },
    },
})

hl.config({
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 30,
        --10
        blur = {
            enabled = true,
            size = 8,
            passes = 2,
            xray = false,
            new_optimizations = true,
            vibrancy = 1.0,
            vibrancy_darkness = 1.0,
        },
        shadow = {
            enabled = true,
            range = 8,
            render_power = 1,
            color = "rgba(bbbb40cc)",
            color_inactive = "rgba(00000000)",
        },
        --drop_shadow = true
        --shadow_range = 8 
        --shadow_render_power = 2
        --col.shadow = rgba(00b7a1cc) #rgba(00b7a1ff) #rgba(77ee00ff)
    },
})

hl.config({
    animations = {
        enabled = true,
        -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
})

hl.config({
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        pseudotile = true,
        -- master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true,
        -- you probably want this
    },
})

hl.config({
    master = {
        -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        -- new_is_master = true
    },
})

hl.config({
    gestures = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        workspace_swipe = false,
    },
})

hl.config({
    misc = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
    },
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.

hl.window_rule({
    name  = "suppressevent_maximi",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- You'll probably like this

hl.window_rule({
    name  = "opacity_1_0_0_90",
    match = {
        class = ".*",
    },
    opacity = "1.0 0.90",
})

hl.window_rule({
    name  = "opacity_0_93",
    match = {
        class = "^(Code)$",
    },
    opacity = 0.93,
})

hl.window_rule({
    name  = "opacity_0_85",
    match = {
        class = "^(pluma)$",
    },
    opacity = 0.85,
})

hl.window_rule({
    name  = "opacity_0_85_0_8",
    match = {
        class = "^(Thunar)$",
    },
    opacity = "0.85 0.8",
})

hl.window_rule({
    name  = "opacity_0_85_0_8",
    match = {
        class = "^(thunar)$",
    },
    opacity = "0.85 0.8",
})

--windowrulev2 = opacity 0.93 0.83, class:^(Alacritty)$

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

local mainMod = "SUPER"

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("alacritty"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "CONTROL + SHIFT" .. " + " .. "Q", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. "Q", hl.dsp.exec_cmd("wlogout --protocol layer-shell"))

--show the logout windw

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nautilus"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("flameshot full"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("wofi --show drun"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout(nil))

-- dwindle

hl.bind(mainMod .. " + " .. "TAB", hl.dsp.window.fullscreen())

--bind = $mainMod SHIFT, L, exec, swaylock

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CONTROL + right", hl.dsp.resizeactive("20 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CONTROL + left", hl.dsp.resizeactive("-20 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CONTROL + up", hl.dsp.resizeactive("0 -20"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CONTROL + down", hl.dsp.resizeactive("0 20"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", { direction = "l" })

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", { direction = "r" })

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", { direction = "u" })

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", { direction = "d" })

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.config({
    debug = {
        disable_logs = false,
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/libexec/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("waybar")
end)
